services:
  edas.webapp:
    image: ${DOCKER_REGISTRY-}edaswebapp
    build:
      context: .
      dockerfile: EDAS.WebApp/Dockerfile

  edas.worker.sorting:
    image: ${DOCKER_REGISTRY-}edasworkersorting
    build:
      context: .
      dockerfile: EDAS.Worker/Dockerfile

  edas.worker.combinatronics:
    image: ${DOCKER_REGISTRY-}edasworkercombinatronics
    build:
      context: .
      dockerfile: EDAS.Worker/Dockerfile

  rabbitmq:
    image: rabbitmq:4.0-management