services:
  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  edas.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Data Source=EDASWebApp.db
      - RabbitMQConfig__Hostname=${RABBITMQ_CONFIG_HOSTNAME}
      - RabbitMQConfig__Port=${RABBITMQ_CONFIG_PORT}
      - RabbitMQConfig__Username=${RABBITMQ_CONFIG_USERNAME}
      - RabbitMQConfig__Password=${RABBITMQ_CONFIG_PASSWORD}
      - EmailConfig__FromEmail=${EMAIL_CONFIG_FROM_EMAIL}
      - EmailConfig__ApiUrl=${EMAIL_CONFIG_API_URL}
      - EmailConfig__ApiKey=${EMAIL_CONFIG_API_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "6001:8080"
    env_file:
      - .env

  edas.worker.sorting:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8100
      - ASPNETCORE_URLS=http://0.0.0.0:8100
      - RabbitMQConfig__Hostname=${RABBITMQ_CONFIG_HOSTNAME}
      - RabbitMQConfig__Port=${RABBITMQ_CONFIG_PORT}
      - RabbitMQConfig__Username=${RABBITMQ_CONFIG_USERNAME}
      - RabbitMQConfig__Password=${RABBITMQ_CONFIG_PASSWORD}
      - EmailConfig__FromEmail=${EMAIL_CONFIG_FROM_EMAIL}
      - EmailConfig__ApiUrl=${EMAIL_CONFIG_API_URL}
      - EmailConfig__ApiKey=${EMAIL_CONFIG_API_KEY}
      - WorkerType__Type=Sorting
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8100:8100"
    env_file:
      - .env

  edas.worker.combinatronics:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8097
      - ASPNETCORE_URLS=http://0.0.0.0:8097
      - RabbitMQConfig__Hostname=${RABBITMQ_CONFIG_HOSTNAME}
      - RabbitMQConfig__Port=${RABBITMQ_CONFIG_PORT}
      - RabbitMQConfig__Username=${RABBITMQ_CONFIG_USERNAME}
      - RabbitMQConfig__Password=${RABBITMQ_CONFIG_PASSWORD}
      - EmailConfig__FromEmail=${EMAIL_CONFIG_FROM_EMAIL}
      - EmailConfig__ApiUrl=${EMAIL_CONFIG_API_URL}
      - EmailConfig__ApiKey=${EMAIL_CONFIG_API_KEY}
      - WorkerType__Type=Combinatronics
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8097:8097"
    env_file:
      - .env