services:
  edasusersdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:4.0-management

  edas.webapp:
    image: ${DOCKER_REGISTRY-}edaswebapp
    build:
      context: .